GET http://localhost:4000/videos

###
GET http://localhost:4000/videos/1

### Create a video
POST http://localhost:4000/videos
Content-Type: application/json

{
    "title": "This is a video description",
    "description": "This is a youtube course video",
    "url": "https://www.youtube.com/watch?v=_RZ-T6TxP7w&t"
}

###
PUT http://localhost:4000/videos/1

###
DELETE http://localhost:4000/videos/1