### all my videos
GET http://localhost:4000/videos

### Only 1 video
GET http://localhost:4000/videos/5f966809604c5c39bc180183

### Create a video
POST http://localhost:4000/videos
Content-Type: application/json

{
    "title": "This is a video description",
    "description": "This is a youtube course video",
    "url": "https://www.youtube.com/watch?v=_RZ-T6TxP7w&t"
}

### update a video
PUT http://localhost:4000/videos/5f966809604c5c39bc180183
Content-Type: application/json

{
    "title": "hi"
}

### Delete
DELETE http://localhost:4000/videos/5f95710e58aa3239643917ca